import {ArrowRight,BrainCircuit,ChevronRight,Cuboid,Heart,Play,ShieldCheck,Sparkles} from 'lucide-react';
import './mico-landing.css';

type Props={onNavigate:(path:'/login'|'/signup')=>void;onDemo:()=>void};
const pathways=[['01','See it in 3D','Rotate real anatomy and inspect structures from every angle.'],['02','Make the connection','Solve short, visual challenges that explain what each part does.'],['03','Remember it','Build a study streak with smart practice, XP, and progress you can keep.']];

export default function MicoLanding({onNavigate,onDemo}:Props){
 return <main className="mico-landing">
  <header className="mico-landing-nav"><button className="mico-landing-brand" onClick={()=>scrollTo({top:0,behavior:'smooth'})}><span>m</span>Mico</button><nav aria-label="Mico overview"><a href="#how-it-works">How it works</a><a href="#learn-anywhere">Explore in 3D</a><a href="#study-loop">Study loop</a></nav><div><button className="mico-landing-login" onClick={()=>onNavigate('/login')}>Log in</button><button className="mico-landing-signup" onClick={()=>onNavigate('/signup')}>Start learning</button></div></header>
  <section className="mico-landing-hero"><div className="mico-landing-copy"><span className="mico-landing-eyebrow"><Sparkles size={14}/> INTERACTIVE ANATOMY</span><h1>Learn the body by <em>exploring</em> it.</h1><p>Mico turns anatomy into a playful visual practice. See real structures in 3D, answer meaningful challenges, and come back knowing more.</p><div className="mico-landing-actions"><button className="mico-landing-primary" onClick={()=>onNavigate('/signup')}>Start for free <ArrowRight size={18}/></button><button className="mico-landing-secondary" onClick={onDemo}><Play size={17} fill="currentColor"/>Try the demo</button></div><small>No credit card. Your first anatomy path is ready.</small></div><div className="mico-landing-orbit" aria-hidden="true"><i className="mico-orbit-ring ring-a"/><i className="mico-orbit-ring ring-b"/><span className="mico-orbit-label label-heart"><Heart size={17} fill="currentColor"/> Heart</span><span className="mico-orbit-label label-bone"><Cuboid size={17}/> 3D lab</span><img src="/mico/mascots/mico-study.png" alt=""/></div></section>
  <section className="mico-landing-proof"><div><b>3D anatomy</b><span>Real structures to rotate and inspect</span></div><div><b>Short lessons</b><span>Made for curious minds, not cramming</span></div><div><b>Your progress</b><span>XP, hearts, streaks, and study history</span></div></section>
  <section className="mico-landing-section mico-landing-path" id="how-it-works"><div><span className="mico-landing-eyebrow dark"><BrainCircuit size={15}/> A BETTER STUDY ROUTINE</span><h2>Your next lesson always has a reason.</h2><p>Start with the foundations, discover body systems one piece at a time, and use practice to make tricky ideas stick.</p><button className="mico-landing-text" onClick={()=>onNavigate('/signup')}>Build your anatomy path <ChevronRight size={17}/></button></div><ol>{pathways.map(([number,title,description])=><li key={number}><i>{number}</i><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></section>
  <section className="mico-landing-model" id="learn-anywhere"><div className="mico-model-art"><span>MOVE · ZOOM · DISCOVER</span><img src="/study/anatomy/heart/organ.webp" alt="A detailed human heart model"/><i className="model-hotspot hot-a">Aorta</i><i className="model-hotspot hot-b">Left ventricle</i></div><div><span className="mico-landing-eyebrow"><Cuboid size={15}/> LEARN WITH YOUR HANDS</span><h2>Not another wall of flashcards.</h2><p>Turn structures around. Zoom in. Make a prediction, then reveal the answer. Mico uses the atlas as part of the lesson—not as a separate textbook.</p><button className="mico-landing-primary" onClick={onDemo}>Open the 3D demo <ArrowRight size={18}/></button></div></section>
  <section className="mico-landing-section mico-landing-loop" id="study-loop"><div><span className="mico-landing-eyebrow dark"><ShieldCheck size={15}/> A GENTLE GAME LOOP</span><h2>Small wins become real knowledge.</h2><p>Every answer changes your progress. Earn XP for correct reasoning, protect your hearts, and revisit concepts until they feel familiar.</p><button className="mico-landing-text" onClick={onDemo}>See your practice lab <ChevronRight size={17}/></button></div><div className="mico-loop-cards"><article><img src="/mico/status/streak-flame.png" alt=""/><b>Keep your streak</b><span>Return for a short review.</span></article><article><img src="/mico/status/study-gem.png" alt=""/><b>Earn XP</b><span>Watch your map grow.</span></article><article><img src="/mico/status/heart-life.png" alt=""/><b>Practise safely</b><span>Mistakes point to what to study.</span></article></div></section>
  <section className="mico-landing-final"><img src="/mico/mascots/mico-celebrate.png" alt="Mico celebrates learning"/><div><span>YOUR BODY. YOUR MAP.</span><h2>Ready to see anatomy differently?</h2><button className="mico-landing-primary" onClick={()=>onNavigate('/signup')}>Create your free account <ArrowRight size={18}/></button></div></section>
  <footer className="mico-landing-footer"><div><button className="mico-landing-brand" onClick={()=>scrollTo({top:0,behavior:'smooth'})}><span>m</span>Mico</button><p>Interactive anatomy for anyone curious about how the body works.</p></div><div><b>Explore</b><a href="#how-it-works">Learning path</a><a href="#learn-anywhere">3D atlas</a><a href="#study-loop">Practice</a></div><div><b>Account</b><button onClick={()=>onNavigate('/login')}>Log in</button><button onClick={()=>onNavigate('/signup')}>Create account</button><button onClick={onDemo}>Public demo</button></div></footer>
 </main>;
}
