import {useEffect,useState,type FormEvent} from 'react';
import {ArrowRight,Check,Eye,EyeOff,LogIn,Mail,Play,ShieldCheck,Sparkles} from 'lucide-react';
import {supabase} from './supabase';
import './mico-auth.css';

type Props={onDemo:()=>void;initialMode:'login'|'signup';onNavigate:(path:'/'|'/login'|'/signup')=>void};
export default function MicoAuth({onDemo,initialMode,onNavigate}:Props){
 const [mode,setMode]=useState<'login'|'signup'>(initialMode);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{setMode(initialMode);setError('');setMessage('')},[initialMode]);
 const submit=async(event:FormEvent)=>{event.preventDefault();setError('');setMessage('');if(!supabase){setError('Supabase is not configured in this environment.');return}if(password.length<8){setError('Use at least 8 characters for your password.');return}setLoading(true);try{if(mode==='login'){const {error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError)throw signInError}else{const {data,error:signUpError}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(signUpError)throw signUpError;setMessage(data.session?'Your Mico account is ready.':'Check your inbox to confirm your Mico account.')}}catch(reason){setError(reason instanceof Error?reason.message:'Something went wrong. Please try again.')}finally{setLoading(false)}};
 const google=async()=>{setError('');if(!supabase){setError('Supabase is not configured in this environment.');return}setLoading(true);const {error:oauthError}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(oauthError){setError(oauthError.message);setLoading(false)}};
 return <main className="mico-auth"><section className="mico-auth-story"><button className="mico-auth-brand" onClick={()=>onNavigate('/')}><span>m</span>Mico</button><div className="mico-auth-orbit orbit-a"/><div className="mico-auth-orbit orbit-b"/><div className="mico-auth-story-copy"><span>INTERACTIVE ANATOMY</span><h1>Build your mental map of the human body.</h1><p>Short lessons, living 3D models, and a study routine that remembers where you left off.</p><ul><li><Check size={16}/>Your progress follows you across devices</li><li><Check size={16}/>Practice with structure-level feedback</li><li><Check size={16}/>Keep your private study data private</li></ul></div><img src="/mico/mascots/mico-study.png" alt="Mico studies an anatomical heart"/></section><section className="mico-auth-panel"><div className="mico-auth-card"><div className="mico-auth-card-top"><button className="mico-auth-demo-top" onClick={onDemo}><Play size={14} fill="currentColor"/>Explore demo</button><div className="mico-auth-mark"><Sparkles size={18}/></div></div><div className="mico-auth-copy"><span>{mode==='login'?'WELCOME BACK':'START YOUR LAB'}</span><h2>{mode==='login'?'Log in to Mico':'Create your Mico account'}</h2><p>{mode==='login'?'Pick up exactly where you left off.':'Save your anatomy progress, achievements, and study sets.'}</p></div><form onSubmit={submit}><label>Email address<div><Mail size={17}/><input value={email} onChange={event=>setEmail(event.target.value)} type="email" autoComplete="email" placeholder="you@example.com" required/></div></label><label>Password<div><ShieldCheck size={17}/><input value={password} onChange={event=>setPassword(event.target.value)} type={showPassword?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} placeholder="At least 8 characters" required/><button type="button" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(value=>!value)}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<p className="mico-auth-error" role="alert">{error}</p>}{message&&<p className="mico-auth-message" role="status">{message}</p>}<button className="mico-auth-submit" disabled={loading}>{loading?'One moment…':mode==='login'?'Log in':'Create account'}<ArrowRight size={18}/></button></form><div className="mico-auth-separator"><span/>or continue with<span/></div><button className="mico-auth-google" onClick={google} disabled={loading}><b>G</b>Continue with Google</button><button className="mico-auth-demo" onClick={onDemo}><LogIn size={17}/>Use a limited public demo</button><p className="mico-auth-switch">{mode==='login'?"New to Mico?":"Already have an account?"} <button onClick={()=>onNavigate(mode==='login'?'/signup':'/login')}>{mode==='login'?'Sign up':'Log in'}</button></p><p className="mico-auth-legal">By continuing, you agree to Mico’s learning data policy. Demo activity is temporary and never mixed with a personal account.</p></div></section></main>;
}
