export type StudyId='heart'|'brain'|'lungs'|'liver'|'kidneys'|'eyeball'|'intestine'|'pancreas'|'skin';
export type StudyHotspot={id:string;label:string;detail:string;position:[number,number,number];color:string};
export type StudyOrgan={id:StudyId;name:string;aliases:string[];model:string;accent:string;summary:string;facts:{label:string;value:string}[];hotspots:StudyHotspot[];};
const asset=(id:StudyId,kind:'organ'|'location'|'microscopic'|'compare')=>`/study/anatomy/${id}/${kind}.webp`;
export const studyAsset=(id:StudyId,kind:'organ'|'location'|'microscopic'|'compare')=>asset(id,kind);
export const STUDY_ORGANS:StudyOrgan[]=[
 {id:'heart',name:'Heart',aliases:['heart'],model:'/study/models/heart.glb',accent:'#ee7c6a',summary:'A muscular pump that sends blood to the lungs and the rest of the body.',facts:[{label:'Location',value:'Behind the sternum, slightly left'},{label:'Function',value:'Circulates oxygenated blood'},{label:'Daily fact',value:'Beats about 100,000 times'}],hotspots:[['aorta','Aorta','Main artery',[-.35,1.65,.55],'#ee7c6a'],['left-atrium','Left atrium','Receives oxygenated blood',[.82,.65,.5],'#f2a33b'],['right-atrium','Right atrium','Receives venous blood',[-.9,.35,.55],'#6393d8'],['left-ventricle','Left ventricle','Pumps to the body',[.7,-.75,.65],'#f2a33b'],['right-ventricle','Right ventricle','Pumps to the lungs',[-.65,-.68,.66],'#ee7c6a'],['mitral','Mitral valve','Prevents backflow',[.18,-1.35,.48],'#d89bc4']]},
 {id:'brain',name:'Brain',aliases:['brain'],model:'/study/models/brain.glb',accent:'#c58696',summary:'The central organ of the nervous system, integrating sensation, memory, emotion, and movement.',facts:[{label:'Location',value:'Protected within the skull'},{label:'Function',value:'Processes and coordinates signals'},{label:'Daily fact',value:'Uses about 20% of the body’s energy'}],hotspots:[['frontal','Frontal lobe','Planning and movement',[-.7,.65,.8],'#ee7c6a'],['parietal','Parietal lobe','Sensory integration',[.15,1.1,.65],'#f2a33b'],['temporal','Temporal lobe','Memory and hearing',[.75,-.1,.82],'#6393d8'],['cerebellum','Cerebellum','Balance and coordination',[.72,-.9,.55],'#d89bc4']]},
 {id:'lungs',name:'Lungs',aliases:['lung','lungs','right lung','left lung'],model:'/study/models/lungs.glb',accent:'#dd8f8b',summary:'Paired organs that exchange oxygen and carbon dioxide across a vast, delicate surface.',facts:[{label:'Location',value:'Either side of the heart in the ribcage'},{label:'Function',value:'Exchanges oxygen for carbon dioxide'},{label:'Daily fact',value:'Moves around 11,000 L of air'}],hotspots:[['trachea','Trachea','Carries air to the lungs',[0,1.6,.2],'#6393d8'],['right-lung','Right lung','Three lobes',[-1.2,.1,.7],'#ee7c6a'],['left-lung','Left lung','Two lobes and room for the heart',[1.2,.1,.7],'#f2a33b'],['bronchus','Bronchus','Branching airway',[-.03,.3,.35],'#d89bc4']]},
 {id:'liver',name:'Liver',aliases:['liver'],model:'/study/models/liver.glb',accent:'#b86858',summary:'A metabolic organ that filters blood, processes nutrients, and produces bile.',facts:[{label:'Location',value:'Upper right abdomen'},{label:'Function',value:'Metabolism, detoxification, and bile'},{label:'Daily fact',value:'Performs more than 500 functions'}],hotspots:[['right-lobe','Right lobe','Largest hepatic lobe',[-.75,.35,.75],'#ee7c6a'],['left-lobe','Left lobe','Crosses the midline',[.85,.25,.75],'#f2a33b'],['portal','Portal vein','Nutrient-rich inflow',[.1,-.3,.82],'#6393d8']]},
 {id:'kidneys',name:'Kidneys',aliases:['kidney','kidneys','right kidney','left kidney'],model:'/study/models/kidneys.glb',accent:'#c96963',summary:'Paired filtration organs that balance fluids, electrolytes, blood pressure, and waste removal.',facts:[{label:'Location',value:'Either side of the spine below the ribs'},{label:'Function',value:'Filters blood and forms urine'},{label:'Daily fact',value:'Filters roughly 180 L of fluid'}],hotspots:[['cortex','Renal cortex','Outer filtering layer',[-.9,.55,.7],'#ee7c6a'],['medulla','Renal medulla','Concentrates urine',[.85,.2,.7],'#f2a33b'],['ureter','Ureter','Carries urine',[.4,-1.1,.5],'#6393d8']]},
 {id:'eyeball',name:'Eye',aliases:['eye','eyeball','right eyeball','left eyeball'],model:'/study/models/eyeball.glb',accent:'#7294b9',summary:'A precision sensory organ that converts focused light into neural signals interpreted as vision.',facts:[{label:'Location',value:'Within the bony orbit'},{label:'Function',value:'Captures and focuses light'},{label:'Daily fact',value:'Makes thousands of tiny movements'}],hotspots:[['cornea','Cornea','Clear focusing surface',[-.94,.05,1.47],'#6393d8'],['iris','Iris','Controls light entry',[-1.22,-.53,1.15],'#f2a33b'],['optic','Optic nerve','Carries visual signals',[1.61,-.18,.54],'#d89bc4']]},
 {id:'intestine',name:'Intestine',aliases:['intestine','small intestine','large intestine','colon','duodenum','jejunum'],model:'/study/models/intestine.glb',accent:'#d78b77',summary:'A folded digestive passage where nutrients are absorbed and the microbiome supports whole-body health.',facts:[{label:'Location',value:'Central and lower abdomen'},{label:'Function',value:'Digestion and nutrient absorption'},{label:'Daily fact',value:'Hosts trillions of microorganisms'}],hotspots:[['duodenum','Duodenum','First small-intestine segment',[.6,.8,.75],'#f2a33b'],['jejunum','Jejunum','Major absorption region',[-.45,.1,.82],'#ee7c6a'],['colon','Colon','Reclaims water',[.75,-.55,.72],'#6393d8']]},
 {id:'pancreas',name:'Pancreas',aliases:['pancreas'],model:'/study/models/pancreas.glb',accent:'#c69a5e',summary:'A dual-purpose gland that releases digestive enzymes and hormones that steady blood sugar.',facts:[{label:'Location',value:'Behind the stomach'},{label:'Function',value:'Digestive enzymes and insulin'},{label:'Daily fact',value:'Makes about 1.5 L of enzyme-rich juice'}],hotspots:[['head','Head','Cradled by the duodenum',[-1.32,-.36,.55],'#ee7c6a'],['body','Body','Crosses the spine',[.05,.25,.45],'#f2a33b'],['tail','Tail','Reaches the spleen',[1.55,.3,.35],'#6393d8'],['duct','Pancreatic duct','Drains enzymes to the gut',[-.61,.39,.5],'#d89bc4']]},
 {id:'skin',name:'Skin',aliases:['skin','body surface'],model:'/study/models/skin.glb',accent:'#c99277',summary:'The body’s largest organ: a living barrier that senses touch, retains water, and regulates temperature.',facts:[{label:'Location',value:'Covering the entire body'},{label:'Function',value:'Protects, senses, and cools'},{label:'Daily fact',value:'Sheds around 500 million cells'}],hotspots:[['epidermis','Epidermis','Outer protective layer',[-.05,.88,1.4],'#ee7c6a'],['dermis','Dermis','Nerves, vessels, and glands',[.29,.05,1.4],'#f2a33b'],['hypodermis','Hypodermis','Fat and insulation',[-.39,-1.15,1.4],'#6393d8'],['follicle','Hair follicle','Anchors each hair',[.89,-.44,1.4],'#d89bc4']]}
].map(organ=>({...organ,hotspots:organ.hotspots.map(([id,label,detail,position,color])=>({id,label,detail,position,color}))})) as StudyOrgan[];
export function studyForName(name:string){const normalized=name.toLowerCase().replace(/\s+of.*$/,'').trim();return STUDY_ORGANS.find(organ=>organ.aliases.includes(normalized)||organ.aliases.some(alias=>normalized.includes(alias)));}
